# Setup
title:               Local Learner Paper 
tagline:             'Local Learner Page'
description:         'A detailed web page for paper Local Learner - IJCAI-23'
url:                 https://rubensolv.github.io/LocalLearnerIJCAI/
baseurl:             'https://rubensolv.github.io/LocalLearnerIJCAI/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rubens O. Moraes
  url:               https://rubensoliveiramoraes.wordpress.com/
  email:             rubensolv@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
