# Site settings
title: Choosing Well Your Opponents:How to Guide the Synthesis of Programmatic Strategies
email: rubensolv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/LocalLearnerIJCAI" # the subpath of your site, e.g. /blog/
url: "https://rubensolv.github.io/LocalLearnerIJCAI" # the base hostname & protocol for your site

twitter_username:
github_username: rubensolv

# Build settings
markdown: kramdown
